### ISSUE TITLE
add .nimble file

### ISSUE THREAD

**Issue by brentp** [h3rald/nim-miniz#1]
thanks for the work on this library.
I'd like to use this library to support .zip files without requiring the .so like the one in nim/zip/zipfiles.
could you add a .nimble file to the repo?
It looks like someone already registered another, less complete "miniz" package but it could still be installed by nimble with the full URL.

**Comment by brentp** [comment]
only requires, e.g.:
```
version       = "9.1.15"
author        = "Fabio Cevasco"
description   = "nim wrapper for miniz"
license       = "MIT"
```
in a `nim_miniz.nimble` file.

But, after looking, I see this doesn't have much support for zip. would you consider a pull request that adds something like:

```nim
type Zip* = object:
   c_ptr = ptr mz_zip_archive 

proc open*(zip:Zip, path:string, mode:int=fmRead): bool =
   ...

proc extract*(zip:Zip, file:string): bool =
   ## extract a single file

proc extract_all*(zip:Zip): bool =
   ## extract all files
  ...

proc add_file*(zip:Zip, path:string) =
   ## add a file to the zip archive.
```

**Comment by h3rald** [comment]
Ohhh very nice! Thanks a lot! Sure, I'll look into your MR soon and release a new version.

**Comment by brentp** [comment]
Great! thanks. I am making some changes as I work with it. Will adjust and ping here when it seems ready.

**Comment by h3rald** [comment]
Silly question... I noticed you named the nimble file nimminiz.nimble... is that because dashes aren't allowed? Can't remember really... but underscores should be allowed right?

**Comment by brentp** [comment]
not sure. I was having some trouble and I got it to work with that--though it was likely mixed with other changes. I'll experiment and see if nim_miniz would work.

**Comment by brentp** [comment]
I changed the name to `nim_miniz` the zip writing seems to be working well. Tomorrow, I'll be on to the reading stuff so I'll tweak anything that needs it and then let you know.
