### ISSUE TITLE
Cannot convert 256 to uint8

### ISSUE THREAD

**Issue by mantielero** [h3rald/nim-miniz#5]
I am trying to compile an example and it is failing with the following message:

    /.nimble/pkgs/nim_miniz-1.0.0/nim_miniz.nim(891, 133) Error: cannot convert 256 to uint8

The `nim_miniz.nim` file contains:

    mz_zip_flags* {.size: sizeof(cint).} = enum 
      MZ_ZIP_FLAG_CASE_SENSITIVE = 0x00000100, 
      MZ_ZIP_FLAG_IGNORE_PATH = 0x00000200, 
      MZ_ZIP_FLAG_COMPRESSED_DATA = 0x00000400, 
      MZ_ZIP_FLAG_DO_NOT_SORT_CENTRAL_DIRECTORY = 0x00000800

where `0x00000100=256` while line 891 contains `MZ_ZIP_FLAG_CASE_SENSITIVE.uint8`; `uint8` goes from 0 to 255.

**Comment by h3rald** [comment]
This works now (using uint16).
