### ISSUE TITLE
Nimble still fetches 1.0.0?

### ISSUE THREAD

**Issue by teras** [h3rald/nim-miniz#6]
Hello again
Maybe this is not a nim-miniz issue, but I don't know where to ask for help about it.

When I am using nimble install nim-miniz, it still fetches the 1.0.0 version.
In this repository it is clear that the version is 1.0.1. 
Is this something which needs to be reported to nimble ?

**Comment by teras** [comment]
According to the docs, a new tag should be defined, maybe create this new v1.0.1 tag?

**Comment by Wh1teDuke** [comment]
Also this version doesn't compile under nim head.

> Is this something which needs to be reported to nimble ?

Use `nimble install nim-miniz@#head`
https://github.com/nim-lang/nimble#nimble-install

**Comment by h3rald** [comment]
Sorry guys, not had a lot of time lately... if you specify nim-miniz@#head it should fetch the latest master though, what error are you getting?

**Comment by Wh1teDuke** [comment]
`nim_miniz-1.0.0/nim_miniz.nim(244, 21) Error: 'typedesc' metatype is not valid here; typed '=' instead of ':'?`

Seems to be working correctly in miniz head tho.

**Comment by h3rald** [comment]
Done!
