### ISSUE TITLE
Is nim-miniz working under Windows?

### ISSUE THREAD

**Issue by teras** [h3rald/nim-miniz#9]
Hello.
I was trying to port my application from Linux/OSX to Windows. 

Unfortunately when the library calls the method `extract_file_to_string`, I receive an assertion error like this:
```
Error: unhandled exception: /root/.nimble/pkgs/nim_miniz-1.1.0/nim_miniz.nim(945, 11) `mz_zip_reader_file_stat(zip.c.addr, i.mz_uint, fileStat.addr) == MZ_TRUE`  [AssertionError]
```

Does this mean that the library is not supported under Windows?
The zip file I am trying to read is a JAR file, and it loads perfectly on both linux/windows

**Comment by h3rald** [comment]
Uhm... I tried compressing/uncompressing files on Windows using [min](https://github.com/h3rald/min), that internally uses nim-miniz... and I encountered no issues (nim v1.2.0)

**Comment by teras** [comment]
The issues are not in general, only when using the mz_zip_reader_file_stat method which returns false instead of true.
I don't know if it's a nim-miniz or miniz itself issue.

When I use the extract_file instead, it works.
